sudo: false

language: node_js

branches:
  only:
    - master

node_js:
  - 8
  - 10

before_script:
  - npm run lint
  - npm run build
  - npm run bundle

after_script:
  - tsc --noEmit --target es6 --module commonjs test/typings.ts
